### ISSUE TITLE
Session Cookie Secure Flag

### ISSUE THREAD

**Issue by maltehie** [buenaventure/verkel#15]
Moin :)

ich habe eine eigene Instanz für das Landeslager vom VCP Nds hochgezogen. Dabei ist mir aufgefallen das für den session cookie _verkel_session die secure flag nicht gesetzt ist.

 https://owasp.org/www-community/controls/SecureCookieAttribute

Kenne mich mit Ruby leider überhaupt nicht aus, daher weiß ich nicht genau wie ich den cookie selber anpassen kann.
Würde daher darum bitten, dass der cookie angepasst wird.

Vielen Dank!

**Comment by buenaventure** [comment]
Hi,
das wird in Rails eigentlich mit `force_ssl` aktiviert. (https://guides.rubyonrails.org/configuring.html#config-force-ssl,
https://cheatsheetseries.owasp.org/cheatsheets/Ruby_on_Rails_Cheat_Sheet.html#authentication)
In Production ist das auch aktiv, siehe hier: https://github.com/buenaventure/verkel/blob/main/config/environments/production.rb#L52
Hast du den Server in Development laufen? Bei meinen Instanzen sieht jedenfalls alles gut aus.

**Comment by maltehie** [comment]
Ich habe den server in Production laufen siehe Ausgabe von ```docker exec -it verkel bundle exec rake about```


```
About your application's environment
Rails version             7.0.8
Ruby version              ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux-musl]
RubyGems version          3.4.10
Rack version              2.2.8
Middleware                ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper, Warden::Manager
Application root          /verkel
Environment               production
Database adapter          postgresql
Database schema version   20230723191003
```

Cookie Secure Flag ist trotzdem nicht aktiv. Beispiel haft zu sehen in einem wapiti scan
```wapiti -u https://verkel.vcpnds.de --scope punk --flush-attacks --flush-session -m cookieflags```


Wapiti Report: [wapiti-verkel-20241802-02.zip](https://github.com/buenaventure/verkel/files/14324886/wapiti-verkel-20241802-02.zip)

**Comment by buenaventure** [comment]
Closing, most likely caused by wrong configuration of proxy headers.
Alternative solution is to set `assuse_ssl` (https://guides.rubyonrails.org/configuring.html#config-assume-ssl) to true
